baseUrl: "https://brendanduke.ca"
languageCode: "en-US"
title: "Brendan Duke"
theme: "github.com/barklan/hugo-dead-simple"
menu:
  main:
    - name: "<u>H</u>ome"
      url: /
      weight: 1
    - name: "<u>T</u>ags"
      url: "https://brendanduke.ca/tags"
      weight: 3

params:
  description: "Hugo dead simple example"

markup:
  highlight:
    codeFences: true
    style: bw
    lineNumbersInTable: false
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - html
    - rss
    - json
  page:
    - html

module:
  imports:
    - path: github.com/barklan/hugo-dead-simple
